# fly.toml app configuration file generated for habitica-dark-field-7411 on 2025-08-21T18:42:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'habitica-dark-field-7411'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  mounts = [
    { source = "rewards_data", destination = "/data" }
  ]

[mounts]
  source="rewards_data"
  destination="/data"
